"use client";

import Image from "next/image";
import styles from "./page.module.css";
import {
  AppBar,
  Avatar,
  Box,
  Card,
  CardActionArea,
  CardContent,
  CardMedia,
  Container,
  Fab,
  Grid,
  IconButton,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  ListSubheader,
  Paper,
  Toolbar,
  Typography,
} from "@mui/material";
import Button from "@/components/Button/Button";
import React from "react";
import { styled } from "@mui/material/styles";
import ButtonCT from "@/components/Button/Button";
var _ = require("lodash");
import { FixedSizeList, ListChildComponentProps } from "react-window";
import { FaCirclePlus, FaCircleMinus, FaTrash } from "react-icons/fa6";

const StyledFab = styled(Fab)({
  position: "absolute",
  zIndex: 1,
  top: -30,
  left: 0,
  right: 0,
  margin: "0 auto",
});

interface Messages {
  id: number;
  primary: string;
  secondary: string;
  person: string;
  mode: string;
}

const messages: Messages[] = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
    mode: "ice",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
    mode: "ice",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    mode: "ice",
    person: "/static/images/avatar/2.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    mode: "ice",
    person: "/static/images/avatar/3.jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    mode: "food",
    person: "/static/images/avatar/4.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    mode: "ice",
    person: "/static/images/avatar/1.jpg",
  },
];

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));

function renderRow(props: ListChildComponentProps) {
  const { index, style } = props;

  return (
    <ListItem style={style} key={index} component="div" disablePadding>
      <ListItemText primary={`Item ${index + 1}`} />
    </ListItem>
  );
}

export default function Home() {
  const dataOrder = _.groupBy(messages, "mode");
  return (
    <Box component="main" sx={{ px: { xs: 0, md: 2 } }}>
      <Grid container spacing={2}>
        <Grid item xs={12} md={7} xl={9}>
          <Box>
            <Typography
              variant="h5"
              gutterBottom
              component="div"
              sx={{ pt: 2, pb: 0 }}
            >
              Order
            </Typography>

            <Box sx={{ overflow: "auto", height: "90vh" }}>
              {Object.keys(dataOrder).map((val, id) => {
                const res: Messages[] = dataOrder[val];
                return (
                  <React.Fragment key={id}>
                    <Typography variant="h5" component="h2" sx={{ my: 2 }}>
                      {val}
                    </Typography>

                    <Grid container spacing={2}>
                      {res.map((valMap, idx) => {
                        return (
                          <Grid
                            item
                            xs={12}
                            sm={12}
                            md={6}
                            lg={4}
                            xl={2}
                            key={idx}
                          >
                            <Card>
                              <CardActionArea
                                sx={{
                                  display: { xs: "flex", md: "block" },
                                  justifyContent: "flex-start",
                                }}
                              >
                                <CardMedia
                                  component="img"
                                  sx={{
                                    width: { xs: 151, md: "100%" },
                                    height: { xs: "auto", md: 180 },
                                  }}
                                  image="https://images.immediate.co.uk/production/volatile/sites/30/2013/05/spaghetti-carbonara-382837d.jpg?resize=768,574"
                                  alt="green iguana"
                                />
                                <Box
                                  sx={{
                                    display: "flex",
                                    flexDirection: "column",
                                  }}
                                >
                                  <CardContent
                                    sx={{ flex: { xs: "1 0 auto" } }}
                                  >
                                    <Typography component="div" variant="h6">
                                      Live From Space
                                    </Typography>
                                    <Typography
                                      variant="subtitle1"
                                      color="text.secondary"
                                      component="div"
                                    >
                                      0.00
                                    </Typography>
                                  </CardContent>
                                </Box>
                              </CardActionArea>
                            </Card>
                          </Grid>
                        );
                      })}
                    </Grid>
                  </React.Fragment>
                );
              })}
            </Box>
          </Box>
        </Grid>
        <Grid
          item
          xs={12}
          md={5}
          xl={3}
          sx={{ display: { xs: "none", md: "block" } }}
        >
          <Box sx={{ height: "98%" }}>
            <Typography variant="h5" component="h2" sx={{ my: 2 }}>
              รายการ โต๊ะ 6-2
            </Typography>
            <Box
              sx={{
                width: "100%",
                height: "90%",
                overflowY: "auto",
                bgcolor: "background.paper",
              }}
            >
              <Card sx={{ position: "relative" }}>
                <Box
                  sx={{
                    display: "flex",
                    justifyContent: "flex-start",
                  }}
                >
                  <CardMedia
                    component="img"
                    sx={{
                      width: 150,
                      height: 150,
                    }}
                    image="https://images.immediate.co.uk/production/volatile/sites/30/2013/05/spaghetti-carbonara-382837d.jpg?resize=768,574"
                    alt="green iguana"
                  />
                  <Box
                    sx={{
                      display: "flex",
                      flexDirection: "column",
                      width: "100%",
                    }}
                  >
                    <CardContent sx={{ flex: "1 0 auto" }}>
                      <Typography component="div" variant="h6">
                        Live From Space
                      </Typography>
                      <Typography
                        variant="subtitle1"
                        color="text.secondary"
                        component="div"
                      >
                        0.00
                      </Typography>
                    </CardContent>
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "flex-end",
                        pl: 1,
                        pb: 1,
                      }}
                    >
                      <IconButton aria-label="previous" size="large">
                        <FaCircleMinus />
                      </IconButton>
                      <IconButton aria-label="play/pause">1</IconButton>
                      <IconButton aria-label="next" size="large">
                        <FaCirclePlus />
                      </IconButton>
                      <IconButton aria-label="next" size="large" color="error">
                        <FaTrash />
                      </IconButton>
                    </Box>
                  </Box>
                </Box>
              </Card>
            </Box>
            {/* <Box sx={{ height: "90%" }}></Box> */}
            <Box>
              <Grid container spacing={2}>
                <Grid item xs={6}>
                  <ButtonCT
                    variant="contained"
                    size="large"
                    color="secondary"
                    fullWidth
                  >
                    ยกเลิก
                  </ButtonCT>
                </Grid>
                <Grid item xs={6}>
                  <ButtonCT variant="contained" size="large" fullWidth>
                    สั่งอาหาร
                  </ButtonCT>
                </Grid>
              </Grid>
            </Box>
          </Box>
        </Grid>
      </Grid>

      <AppBar position="fixed" color="primary" sx={{ top: "auto", bottom: 0 }}>
        <Toolbar>
          <IconButton color="inherit" aria-label="open drawer"></IconButton>
          <StyledFab color="secondary" aria-label="add"></StyledFab>
          <Box sx={{ flexGrow: 1 }} />
          <IconButton color="inherit"></IconButton>
          <IconButton color="inherit"></IconButton>
        </Toolbar>
      </AppBar>
    </Box>
  );
}
