"use client";

import Image from "next/image";
import styles from "./page.module.css";
import {
  AppBar,
  Avatar,
  Box,
  Card,
  CardActionArea,
  CardContent,
  CardMedia,
  Container,
  Fab,
  Grid,
  IconButton,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  ListSubheader,
  Paper,
  Toolbar,
  Typography,
} from "@mui/material";
import Button from "@/components/Button/Button";
import React from "react";
import { styled } from "@mui/material/styles";
var _ = require("lodash");

const StyledFab = styled(Fab)({
  position: "absolute",
  zIndex: 1,
  top: -30,
  left: 0,
  right: 0,
  margin: "0 auto",
});

interface Messages {
  id: number;
  primary: string;
  secondary: string;
  person: string;
  mode: string;
}

const messages: Messages[] = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
    mode: "ice",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
    mode: "ice",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    mode: "ice",
    person: "/static/images/avatar/2.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    mode: "ice",
    person: "/static/images/avatar/3.jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    mode: "food",
    person: "/static/images/avatar/4.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    mode: "ice",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    mode: "ice",
    person: "/static/images/avatar/1.jpg",
  },
];

const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#fff",
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: "center",
  color: theme.palette.text.secondary,
}));

export default function Home() {
  const dataOrder = _.groupBy(messages, "mode");
  return (
    <main>
      <Container>
        <Typography
          variant="h5"
          gutterBottom
          component="div"
          sx={{ pt: 2, pb: 0 }}
        >
          Order
        </Typography>

        {Object.keys(dataOrder).map((val, id) => {
          const res: Messages[] = dataOrder[val];
          return (
            <React.Fragment key={id}>
              <Typography variant="h5" component="h2" sx={{ my: 2 }}>
                {val}
              </Typography>

              {/* <ListSubheader sx={{ bgcolor: "background.paper" }}> */}
              <Grid container spacing={2}>
                {res.map((valMap, idx) => {
                  return (
                    <Grid item xs={12} sm={4} md={4} lg={3} key={idx}>
                      <Card>
                        <CardActionArea
                          sx={{
                            display: { xs: "flex", sm: "block" },
                            justifyContent: "flex-start",
                          }}
                        >
                          <CardMedia
                            component="img"
                            sx={{
                              width: { xs: 151, sm: "100%" },
                              height: { xs: "auto", sm: 180 },
                            }}
                            image="https://images.immediate.co.uk/production/volatile/sites/30/2013/05/spaghetti-carbonara-382837d.jpg?resize=768,574"
                            alt="green iguana"
                          />
                          <Box
                            sx={{
                              display: "flex",
                              flexDirection: "column",
                            }}
                          >
                            <CardContent sx={{ flex: { xs: "1 0 auto" } }}>
                              <Typography component="div" variant="h5">
                                Live From Space
                              </Typography>
                              <Typography
                                variant="subtitle1"
                                color="text.secondary"
                                component="div"
                              >
                                Mac Miller
                              </Typography>
                            </CardContent>
                          </Box>
                        </CardActionArea>
                      </Card>
                    </Grid>
                  );
                })}
              </Grid>
            </React.Fragment>
          );
        })}
      </Container>
      <AppBar position="fixed" color="primary" sx={{ top: "auto", bottom: 0 }}>
        <Toolbar>
          <IconButton color="inherit" aria-label="open drawer"></IconButton>
          <StyledFab color="secondary" aria-label="add"></StyledFab>
          <Box sx={{ flexGrow: 1 }} />
          <IconButton color="inherit"></IconButton>
          <IconButton color="inherit"></IconButton>
        </Toolbar>
      </AppBar>
    </main>
  );
}
